publishDir = "../docs"

baseURL = "https://foundriesio.github.io/foundriesiov2/"
title = "Foundries.io"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
[params]
    defaultKeywords = ["microPlatform", "osf", "updates", "ota", "ble", "mesh",
            "raspberrypi3", "rpi", "rtos", "linux", "docker", "containers",
            "secure", "continuous", "automation", "arm", "risc-v", "automotive",
            "edge", "fog", "smart", "sensor", "devices", "software", "foundriesio"]
    defaultDescription = "Our mission is to fulfill the promise of IoT by delivering a continuously-updated software platform for a secure connected world"
    date_format = "January 2, 2006"
    viewMorePostLink = "/insights/"

[Permalinks]
    insights = "/insights/:year/:month/:day/:filename/"

[params.widgets]
    categories = true
    tags = true
    search = true
